/**
 * The pages this site generates rather than writes: the backlog, one page per
 * User Story, the badges index and one page per badge holder.
 *
 * They are built here, once, and called with the words of a locale, so the
 * French backlog cannot drift from the English one: what differs between them
 * is i18n/<locale>.json and nothing else. scripts/build/universe.mjs builds the
 * repository's BACKLOG.md from these, and scripts/build/site.mjs builds the site
 * pages of every locale.
 *
 * Every builder returns markdown without front matter. The caller adds it,
 * because the title, the description and the alternates depend on where the page
 * is published.
 */
import { fill } from "./strings.mjs";

const separator = (columns) => `|${columns.map(() => "---").join("|")}|`;
const row = (cells) => `| ${cells.join(" | ")} |`;

/**
 * The backlog: the table of the stories, each one in full, and the team.
 *
 * storyLink is what a story id points at, which is the site page on the
 * repository copy and the neighbouring file on the site.
 */
export function backlogPage({ universe, s, text, storyLink, generatedBy }) {
  const lines = [];
  if (generatedBy) {
    lines.push(`<!-- Generated by ${generatedBy}. Do not edit by hand. -->`, "");
  }
  lines.push(`# ${s.backlog.heading}`, "", text.pitch(), "", ...s.backlog.intro, "");
  lines.push(row(s.backlog.columns), separator(s.backlog.columns));
  for (const story of universe.userStories) {
    const owner = universe.cast.find((person) => person.handle === story.author);
    const one = text.story(story);
    lines.push(row([
      `[${story.id}](${storyLink(story)})`,
      story.level,
      one.title,
      owner ? text.name(owner) : story.author,
      `\`${story.branch}\``
    ]));
  }
  lines.push("", `## ${s.backlog.inFull}`, "");
  for (const story of universe.userStories) {
    const owner = universe.cast.find((person) => person.handle === story.author);
    const one = text.story(story);
    // Kept for the links written before each story had its own page
    lines.push(`<a id="${story.id}"></a>`, "", `### ${story.id} - ${one.title}`, "");
    lines.push(`**${s.backlog.owner}**: ${owner ? text.name(owner) : story.author}  `);
    lines.push(`**${s.backlog.branch}**: \`${story.branch}\`  `);
    lines.push(`**${s.backlog.lab}**: ${story.level}.${story.lab}`, "");
    lines.push(`> ${one.story}`, "");
    lines.push(s.backlog.acceptance, "");
    for (const criterion of one.acceptance) {
      lines.push(`- ${criterion}`);
    }
    lines.push("");
  }
  lines.push(`## ${s.backlog.team}`, "");
  lines.push(row(s.backlog.teamColumns), separator(s.backlog.teamColumns));
  for (const person of universe.cast) {
    lines.push(row([text.name(person), text.role(person)]));
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * One story page, which is where a ticket link lands: the configuration of the
 * course builds its URL from the id alone.
 */
export function storyPage({ universe, s, text, story, owner, labLink, backlogLink }) {
  const one = text.story(story);
  return [
    `# ${story.id} - ${one.title}`,
    "",
    `> ${one.story}`,
    "",
    s.story.acceptance,
    "",
    ...one.acceptance.map((criterion) => `- ${criterion}`),
    "",
    "| | |",
    "|---|---|",
    row([s.story.owner, owner ? text.name(owner) : story.author]),
    row([s.story.branch, `\`${story.branch}\``]),
    row([s.story.deliveredIn, labLink]),
    "",
    `[${s.story.backToBacklog}](${backlogLink})`,
    ""
  ].join("\n");
}

/** The badges index: everybody who claimed one, and how to claim yours. */
export function badgesPage({ s, holders, badgeHref, badgeImage, claimUrl, recordUrlPattern, bannerExample }) {
  const rows = holders.map((holder) => {
    // An <img> and not markdown: the badge is drawn 320 square, and a table cell
    // wants a thumbnail. Plain HTML sizes it without depending on an extension.
    const image = holder.highest
      ? `<img src="${badgeImage(holder.key, holder.highest.level)}" alt="${holder.highest.name}" width="72"/>`
      : "";
    const trailblazer = holder.trailblazer
      ? `[${holder.trailblazer}](https://www.salesforce.com/trailblazer/${holder.trailblazer})`
      : "";
    const github = holder.recipient ? `[@${holder.recipient}](https://github.com/${holder.recipient})` : "";
    return row([image, `[${holder.name}](${badgeHref(holder.key)})`, holder.highest ? holder.highest.name : "", github, trailblazer]);
  });

  return [
    `# ${s.badges.heading}`,
    "",
    ...s.badges.intro,
    "",
    holders.length === 0 ? s.badges.nobody : [row(s.badges.columns), separator(s.badges.columns), ...rows].join("\n"),
    "",
    `## ${s.badges.claim.heading}`,
    "",
    ...s.badges.claim.body.map((line) => fill(line, { claimUrl })),
    "",
    `## ${s.badges.readFromElsewhere.heading}`,
    "",
    ...s.badges.readFromElsewhere.intro,
    "",
    "```",
    recordUrlPattern,
    "```",
    "",
    ...s.badges.readFromElsewhere.outro,
    "",
    // The banner a badge ends up in. Trailhead Banner asks for a Trailblazer
    // username and reads the record above, which is why it sits right after it.
    ...(bannerExample
      ? [
          `## ${s.badges.banner.heading}`,
          "",
          ...s.badges.banner.intro,
          "",
          `![${s.badges.banner.alt}](${bannerExample})`,
          "",
          ...s.badges.banner.outro,
          ""
        ]
      : [])
  ].join("\n");
}

/** The name of the highest badge a holder earned, as a post says it. */
const badgeName = ({ s, holder }) => (holder.highest ? holder.highest.name : s.badges.heading);

/**
 * The post a learner publishes about their badge, in the language of the page.
 *
 * Written in the first person, because the button is pressed by the holder. The
 * badge page comes first, on the opening line: a post shows the preview of one
 * link, and it has to be the page with the learner's card on it, not the course.
 */
export function postText({ s, holder, pageUrl, courseUrl }) {
  return s.badge.postText
    .map((line) => fill(line, { badge: badgeName({ s, holder }), page: pageUrl, course: courseUrl }))
    .join("\n");
}

/**
 * The row of share buttons under a badge.
 *
 * The point of a badge is that somebody shares it, and every network wants its
 * own intent URL. LinkedIn comes first because that is where a Salesforce
 * credential lands; the others are there so nobody has to copy the URL by hand.
 * Each one carries the page, which is what holds the card a feed renders, and a
 * line of text for the networks that take one.
 *
 * LinkedIn's documented share URL takes the page and nothing else: it has
 * ignored any text since 2019, so it opened an empty post. The composer URL of
 * the feed takes the whole post instead. It is not documented, which is why the
 * same text is also on the page, to copy, for the day it stops working.
 */
function shareButtons({ s, holder, pageUrl, post }) {
  const url = encodeURIComponent(pageUrl);
  const text = encodeURIComponent(fill(s.badge.shareText, { name: holder.name, badge: badgeName({ s, holder }) }));
  const networks = [
    { label: s.badge.networks.linkedin, href: `https://www.linkedin.com/feed/?shareActive=true&text=${encodeURIComponent(post)}`, primary: true },
    { label: s.badge.networks.x, href: `https://twitter.com/intent/tweet?url=${url}&text=${text}` },
    { label: s.badge.networks.facebook, href: `https://www.facebook.com/sharer/sharer.php?u=${url}` },
    { label: s.badge.networks.bluesky, href: `https://bsky.app/intent/compose?text=${text}%20${url}` },
    { label: s.badge.networks.whatsapp, href: `https://wa.me/?text=${text}%20${url}` },
    { label: s.badge.networks.email, href: `mailto:?subject=${text}&body=${url}` }
  ];
  return [
    networks
      .map((one) => `[${one.label}](${one.href}){ .md-button${one.primary ? " .md-button--primary" : ""} }`)
      .join("\n")
  ];
}

/**
 * One badge holder's page, from the record the claim wrote.
 *
 * The record is the source: the page is built from it on every site build, in
 * every language, so a claim never has to write a page per locale and an old
 * badge gains the new languages by itself.
 */
export function badgePage({ s, holder, badgeImage, bannerImage, postImage, courseUrl, pageUrl, recordUrl }) {
  // The holder, not the raw record: a record written before names were stored
  // has only its key, and site.mjs is where that is filled in. Reading the
  // record here put "undefined" on the page while the index listed the person
  // correctly.
  const record = holder.record;
  // Level order, always: a record holds them in the order the claims arrived,
  // and a page that lists Release Manager above Contributor Basics reads as if
  // the levels had no order at all.
  const badges = [...(record.badges || [])].sort((one, other) => one.level - other.level);
  const rows = badges.map((badge) => row([
    `![${badge.name}](${badgeImage(badge.level)})`,
    `**${badge.name}**`,
    badge.issuedOn,
    fill(s.badge.checks, { passed: badge.checksPassed, total: badge.checksTotal })
  ]));
  // The banner version of each badge earned, in level order. A learner can hold
  // three of them, and the row says so; each picture is shared by everybody of
  // that level, which is what makes an address worth publishing.
  const inBanner = bannerImage ? badges.filter((badge) => badge.bannerImage) : [];

  const evidence = badges[0] && badges[0].evidence && badges[0].evidence[0];
  const repository = evidence && evidence.url
    ? `[${s.badge.meaning.repository}](${evidence.url})`
    : s.badge.meaning.fallbackRepository;

  return [
    `# ${fill(s.badge.heading, { name: holder.name })}`,
    "",
    holder.recipient ? `${s.badge.github}: [@${holder.recipient}](https://github.com/${holder.recipient})` : "",
    holder.trailblazer
      ? `<br/>${s.badge.trailblazer}: [${holder.trailblazer}](https://www.salesforce.com/trailblazer/${holder.trailblazer})`
      : "",
    "",
    row(s.badge.columns),
    separator(s.badge.columns),
    ...rows,
    "",
    `## ${s.badge.meaning.heading}`,
    "",
    ...s.badge.meaning.body.map((line) => fill(line, { repository })),
    "",
    `## ${s.badge.notCertification.heading}`,
    "",
    ...s.badge.notCertification.body,
    "",
    ...(inBanner.length > 0
      ? [
          `## ${s.badge.banner.heading}`,
          "",
          inBanner
            .map((badge) => `![${badge.name}](${bannerImage(badge.level)}){ width="72" }`)
            .join(" "),
          "",
          ...s.badge.banner.body,
          "",
          "```",
          ...inBanner.map((badge) => badge.bannerImage),
          "```",
          "",
          recordUrl ? `[${s.badge.banner.record}](${recordUrl})` : "",
          ""
        ]
      : []),
    ...(pageUrl ? shareSection({ s, holder, pageUrl, courseUrl, postImage }) : []),
    `[${s.badge.takeTheCourse}](${courseUrl}){ .md-button }`,
    ""
  ].join("\n");
}

/**
 * Where a learner shares their badge: the post, already written, the buttons,
 * and the square picture to attach.
 *
 * The post is a code block for the copy button the theme puts on every one, so
 * the page needs no script of its own. A link in a LinkedIn post only ever
 * shows as a thumbnail; the picture, downloaded and attached, is the one way the
 * badge shows full width, and the steps say how. Without a picture, which is a
 * claim that ran without a browser, that part is left out rather than broken.
 */
function shareSection({ s, holder, pageUrl, courseUrl, postImage }) {
  const post = postText({ s, holder, pageUrl, courseUrl });
  const alt = fill(s.badge.picture.alt, { name: holder.name, badge: badgeName({ s, holder }) });
  return [
    `## ${s.badge.shareHeading}`,
    "",
    s.badge.shareIntro,
    "",
    '<div class="badge-post" markdown>',
    "",
    "```text",
    post,
    "```",
    "",
    "</div>",
    "",
    ...shareButtons({ s, holder, pageUrl, post }),
    "",
    ...(postImage
      ? [
          `### ${s.badge.picture.heading}`,
          "",
          ...s.badge.picture.body,
          "",
          ...s.badge.picture.steps.map((step, index) => `${index + 1}. ${step}`),
          "",
          `![${alt}](${postImage}){ width="360" }`,
          "",
          `[${s.badge.picture.download}](${postImage}){ .md-button download="sfdx-hardis-badge-${holder.key}.png" }`,
          ""
        ]
      : [])
  ];
}
